DROP SCHEMA IF EXISTS LIBRARY;
CREATE SCHEMA LIBRARY;
USE LIBRARY;

DROP SCHEMA IF EXISTS LIBRARY;
CREATE SCHEMA LIBRARY;
USE LIBRARY;

CREATE TABLE BOOK (
	ISBN10 VARCHAR(10) NOT NULL,
	TITLE VARCHAR(300) CHARACTER SET UTF8 NOT NULL,
	PRIMARY KEY(ISBN10)
);

CREATE TABLE AUTHORS (
    AUTHOR_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) CHARACTER SET UTF8,
    PRIMARY KEY(AUTHOR_ID)
);

CREATE TABLE BOOK_AUTHORS (
    AUTHOR_ID INT UNSIGNED NOT NULL,
    ISBN10 VARCHAR(10) NOT NULL,
    PRIMARY KEY (AUTHOR_ID, ISBN10),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ISBN10) REFERENCES BOOK(ISBN10) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE BORROWER (
    CARD_ID VARCHAR(6) NOT NULL,
    SSN VARCHAR(11) NOT NULL,
    BNAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(250),
    PHONE VARCHAR(15),
    PRIMARY KEY(CARD_ID),
    UNIQUE(SSN)
);	

CREATE TABLE BOOK_LOANS (
	LOAN_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	ISBN10 VARCHAR(10) NOT NULL,
	CARD_ID VARCHAR(6) NOT NULL,
	DATE_OUT DATE,
	DUE_DATE DATE,	
	DATE_IN DATE,
    PRIMARY KEY(LOAN_ID),
    FOREIGN KEY (CARD_ID) REFERENCES BORROWER(CARD_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ISBN10) REFERENCES BOOK(ISBN10) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE FINES (
    LOAN_ID INT UNSIGNED NOT NULL,
    FINE_AMT DECIMAL(5,2),
    PAID BOOLEAN,
    PRIMARY KEY(LOAN_ID),
    FOREIGN KEY (LOAN_ID) REFERENCES BOOK_LOANS(LOAN_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
COMMIT;